version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: development
    expose: 
      - 3000
    ports:
      - 3030:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - mongo

#   mongodb:
#     restart: always
#     image: mongo:4.2.0
#     volumes:
#       - ./data:/data/db
#     networks:
#       - express-mongo
#     expose:
#       - 27017