version: "3.9"

services:
  frontend:
    container_name: client
    build:
      context: ./frontend
      # target: development
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - backend
    networks:
      - next-express

  backend:
    container_name: server
    restart: always
    build:
      context: ./backend
      # target: development
      dockerfile: Dockerfile
    expose: 
      - 3000
    ports:
      - 3030:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - express-mongo
      - next-express

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    expose:
      - 27017
    ports:
      - 27018:27017
    networks:
      - express-mongo

networks:
  next-express:
  express-mongo: